### PR TITLE
Fix issue with sqlite3 causing electron to crash

### PR DESCRIPTION
**Pull request by ksambhi**
This PR fixes an issue with sqlite causing a segment fault (#6).

### CODE REVIEW

**Comment by jujhars13** [comment]
Looks good sorry for the delay, was in London all week, just going to test now,

**Comment by ksambhi** [comment]
Thanks

**Comment by jujhars13** [comment]
Not quite working properly, but going to merge in anyway and tweak from there.  Is this compiling well on your windows machine
?

**Comment by ksambhi** [comment]
Compiles well on my PC.  I recommend you run `. ./setup-x64` (loads environment variables) and then `HOME=~/.electron-gyp npm install`

**Comment by jujhars13** [comment]
fixed: had to update my global version of NPM to get this to work

**Comment by ksambhi** [comment]
Ok

**Pull request merged**
